# Generated by Django 5.2.7 on 2025-10-26 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hieroglyph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('transcription', models.CharField(max_length=50)),
                ('translation', models.CharField(max_length=100)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hieroglyphs', to='hieroglyphs.dictionary')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=200)),
                ('words', models.TextField()),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='hieroglyphs.dictionary')),
            ],
        ),
    ]
