# Generated by Django 5.2.7 on 2025-10-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hieroglyphs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hieroglyph',
            old_name='symbol',
            new_name='character',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='words',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentence',
            name='hieroglyphs',
            field=models.ManyToManyField(to='hieroglyphs.hieroglyph'),
        ),
    ]
